### ISSUE TITLE
Only Unified Margin Trade Account Are Supported

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean.Brokerages.ByBit#24]
#### Expected Behavior
Be able to deploy algorithms using newly created API keys.

#### Actual Behavior
We get this message:
![Only Unified Margin Trade Account Are Supported](https://github.com/user-attachments/assets/e13d4b10-9167-4c44-8951-5d0a2c0aa30d)

#### Potential Solution
Review connection.

#### Reproducing the Problem
Deploy any algorithm with newly created API keys.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by zurpet** [comment]
Hi, we've been looking into this, it looks like Bybit has changed the status codes for **unifiedMarginStatus**, specifically:

- 1 Classic account
- 3 Unified trading account 1.0
- 4 Unified trading account 1.0 (pro version)
- 5 Unified trading account 2.0
- 6 Unified trading account 2.0 (pro version)

Link:
[https://bybit-exchange.github.io/docs/v5/enum#unifiedmarginstatus](https://bybit-exchange.github.io/docs/v5/enum#unifiedmarginstatus)

**Comment by zurpet** [comment]
Bybit API now returns code 6 for unifiedMarginStatus:
`20240922 17:27:42.274 DEBUG:: Bybit request for /v5/account/info executed successfully. Response: {"retCode":0,"retMsg":"OK","result":{"marginMode":"REGULAR_MARGIN","updatedTime":"1707745286000","unifiedMarginStatus":6,"dcpStatus":"OFF","timeWindow":0,"smpGroup":0,"isMasterTrader":false,"spotHedgingStatus":"OFF"}}`

But in the bybit brokerage code, it only expects values 3 or 4 (but gets 6):
```
    private static bool IsAccountMarginStatusValid(BybitApi api, out BrokerageMessageEvent message)
    {
        var accountInfo = api.Account.GetAccountInfo();
        if (accountInfo.UnifiedMarginStatus is not (AccountUnifiedMarginStatus.UnifiedTrade
            or AccountUnifiedMarginStatus.UTAPro))
        {
            message = new BrokerageMessageEvent(BrokerageMessageType.Error, -1,
                "Only unified margin trade accounts are supported");
            return false;
        }

        message = null;
        return true;
    }



public enum AccountUnifiedMarginStatus
{
    /// <summary>
    /// Regular account
    /// </summary>
    [EnumMember(Value = "1")] Regular = 1,

    /// <summary>
    /// Unified margin account, it only trades linear perpetual and options.
    /// </summary>
    [EnumMember(Value = "2")] UnifiedMargin = 2,

    /// <summary>
    /// Unified trade account, it can trade linear perpetual, options and spot
    /// </summary>
    [EnumMember(Value = "3")] UnifiedTrade = 3,

    /// <summary>
    /// UTA Pro, the pro version of Unified trade account
    /// </summary>
    [EnumMember(Value = "4")] UTAPro = 4,
}
```

**Comment by zurpet** [comment]
So all in all, we need to reflect the new unifiedMarginStatus values in the AccountUnifiedMarginStatus enum, otherwise we are stuck and cannot start strategies LIVE
