### ISSUE TITLE
Exception during funding when running live

### ISSUE THREAD

**Issue by arodus** [QuantConnect/Lean.Brokerages.ByBit#7]
When running live and there is an open position when funding happens an exception is thrown and the algo stops. Apparently, I never had a trade open during funding when I was initially testing this brokerage 🙈 

#### Expected Behavior

The brokerage handles the funding ws message properly. 

#### Actual Behavior

A serialization exception is thrown cause there is no `OrderType` which equals `UNKNOWN`

#### Potential Solution

Add `UNKNOWN` to the `OrderType` enum and handle the funding message properly. @Martin-Molinero do we need to submit an order update when funding occurs? 

#### Reproducing the Problem

Having an open order when funding occurs. I unfortunately don't have the exact log anymore.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @arodus! Thanks for the report

> do we need to submit an order update when funding occurs?

No 👍 believe it should be ignored for now. Any cash difference are settled daily by the cash diff
